# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/databases.json
Databases:
  AnyIvySystemDb:
    Url: jdbc:hsqldb:mem:Test
    Driver: org.hsqldb.jdbcDriver
    UserName: ''
    MaxConnections: 50
